version: 2

sources:

    - name: source

      database: MYDB

      schema: BRONZE

      tables:

        - name: WORK_PRODUCT_COPY

version: 2

sources:
  - name: xfm
    database: PC_DBT_DB
    schema: silver
    tables:
      - name: WORK_PRODUCT_TRANSFORM
       